---
- name: Fedora KDE automation
  hosts: localhost
  vars_files:
    - vars/defaults.yml
    - vars/common_software.yml
    - vars/terminal_tools.yml
    - vars/development_software.yml
    - vars/working_software.yml

  tasks:
    - name: Environment configuration
      import_tasks: tasks/set_environment.yml
      when: first_run | default(false) or 'environment' in ansible_run_tags
      tags: environment

    - name: Fetch user's home configurations
      import_tasks: tasks/fetch_home.yml
      when: first_run | default(false) or 'home' in ansible_run_tags
      tags: home

    - name: Common software
      import_tasks: tasks/install_software.yml
      vars:
        software: "{{ common_software }}"
      tags: common

    - name: Terminal tools
      import_tasks: tasks/install_software.yml
      vars:
        software: "{{ terminal_tools }}"
      tags: terminal

    - name: Zsh and shell tools
      import_tasks: tasks/install_shell.yml
      tags: shell

    - name: Set the basic KDE packages
      import_tasks: tasks/adjust_kde_packages.yml
      tags: kde

    - name: Development software
      import_tasks: tasks/install_software.yml
      vars:
        software: "{{ development_software }}"
      tags: development

    - name: Install docker
      import_tasks: tasks/install_docker.yml
      when: first_run | default(false) or 'docker' in ansible_run_tags
      tags: docker

    - name: Working apps
      import_tasks: tasks/install_software.yml
      vars:
        software: "{{ working_software }}"
      when: first_run | default(false) or 'work' in ansible_run_tags
      tags: work

    - name: Disable powersave for Wifi
      import_tasks: tasks/disable_wifi_powersave.yml
      when: first_run | default(false) or 'wifi' in ansible_run_tags
      tags: wifi
