- name: Remove unused packages
  package:
    name:
      - kdebugsettings
      - hplip
      - hplip-gui
      - krfb
      - krfb-libs
    state: absent
  become: true

- name: Install basic KDE packages
  package:
    name:
      - okular
      - gwenview
      - haruna
    state: present
  become: true

- name: Clean DNF cache
  command: dnf clean all
  changed_when: false
  become: true

- name: Remove unused dependencies
  command: dnf autoremove -y
  changed_when: false
  become: true
