- name: Install zsh and tools
  import_tasks: ./install_software.yml
  vars:
    software:
      dnf:
        - zsh
        - fzf
      copr: []
      flatpak: []

- name: Get zsh path
  command: which zsh
  register: zsh_path
  changed_when: false

- name: Install zsh as the default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"
  become: true

- name: Install starship prompt
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: /usr/local/bin/starship
